name: garden_flow
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.4
  logger: ^2.4.0
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  mailer: ^6.2.0
  email_validator: ^3.0.0
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1
  device_info_plus: ^11.1.0
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.0
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "resources/park.png"
  min_sdk_android: 21
flutter:
  uses-material-design: true
  assets:
   - resources/logo.png
   - resources/fertilizer.png
   - resources/pump.png
   - resources/remote.png
   - resources/notification.png
   - resources/icon.png
   - resources/info.png
